// ############################################################################//
//                                                                             //
//    ... перезагрузить z2m, что бы конвертер применился                       //
//                                                                             //
//#############################################################################//


//const reporting = require('zigbee-herdsman-converters/lib/reporting');
//const exposes = require('zigbee-herdsman-converters/lib/exposes');
//const e = exposes.presets;
//const ea = exposes.access;
const {
    binary,
    enumLookup,
    numeric,
	pressure,
	pm25,
	co2,
    temperature,
	humidity,
} = require('zigbee-herdsman-converters/lib/modernExtend');

const defaultReporting = {min: 0, max: 300, change: 0};
const normalReporting = {min: 0, max: 3600, change: 0};
const rareReporting = {min: 0, max: 21600, change: 0};
const rarestReporting = {min: 0, max: 64800, change: 0};
const oneReporting = {min: 45, max: 1800, change: 1};
const twoReporting = {min: 45, max: 1800, change: 10};
const threeReporting = {min: 30, max: 1800, change: 1};
const fourReporting = {min: 30, max: 1800, change: 10};
const fiveReporting = {min: 1800, max: 10600, change: 1};
const sixReporting = {min: 3600, max: 21600, change: 1};
const co2Reporting = {min: 10, max: 600, change: 0.000001};
const pmReporting = {min: 10, max: 600, change: 0.1};
const pm2Reporting = {min: 10, max: 600, change: 0.01};

const definition = {
        zigbeeModel: ['EFEKTA_Smart_AQ_Box_R3'],
        model: 'EFEKTA_Smart_AQ_Box_R3',
        vendor: 'EFEKTA',
        description: 'EFEKTA Smart Air Quality Box, can control the relay, binding on some other devices',
        extend: [
			 numeric({
                name: "pm1",
                unit: "µg/m³",
                cluster: "pm25Measurement",
                attribute: {ID: 0x0601, type: 0x39},
                description: "Measured PM1.0 (particulate matter) concentration",
                access: "STATE",
                reporting: pmReporting,
                precision: 1,
            }),
            pm25({
                reporting: pmReporting,
                access: "STATE",
                description: "Measured PM2.5 (particulate matter) concentration",
                precision: 1,
            }),
            numeric({
                name: "pm4",
                unit: "µg/m³",
                cluster: "pm25Measurement",
                attribute: {ID: 0x0605, type: 0x39},
                description: "Measured PM4.0 (particulate matter) concentration",
                access: "STATE",
                reporting: pmReporting,
                precision: 1,
            }),
            numeric({
                name: "pm10",
                unit: "µg/m³",
                cluster: "pm25Measurement",
                attribute: {ID: 0x0602, type: 0x39},
                description: "Measured PM10.0 (particulate matter) concentration",
                access: "STATE",
                reporting: pmReporting,
                precision: 1,
            }),
            numeric({
                name: "pm_size",
                unit: "µm",
                cluster: "pm25Measurement",
                attribute: {ID: 0x0603, type: 0x39},
                description: "Typical Particle Size",
                access: "STATE",
                reporting: pm2Reporting,
                precision: 2,
            }),
            numeric({
                name: "aqi_25_index",
                unit: "PM2.5 Index",
                cluster: "pm25Measurement",
                attribute: {ID: 0x0604, type: 0x39},
                description: "PM 2.5 INDEX",
                access: "STATE",
                reporting: pmReporting,
            }),
			co2({
				reporting: co2Reporting,
				access: "STATE",
            }),
            numeric({
                name: "voc_index",
                unit: "VOC Index points",
                cluster: "genAnalogInput",
                attribute: "presentValue",
                description: "VOC index",
                access: "STATE",
                reporting: threeReporting,
            }),
            pressure({
                reporting: threeReporting,
                access: 'STATE',
            }),
            temperature({
                reporting: fourReporting,
                access: 'STATE',
            }),
			humidity({
                reporting: fourReporting,
				access: 'STATE',
            }),
            numeric({
                name: "reading_delay",
                unit: "sec",
                valueMin: 6,
                valueMax: 600,
                cluster: "msCO2",
                attribute: {ID: 0x0201, type: 0x21},
                description: "Setting the sensor reading delay.",
                access: "STATE_SET",
            }),
			binary({
                name: "alarm",
				valueOn: ["ON", 1],
                valueOff: ["OFF", 0],
                cluster: "msCO2",
                attribute: {ID: 0x0240, type: 0x10},
                description: "Alarm",
                access: "STATE_SET",
            }),
			binary({
                name: "light_indicator",
                valueOn: ["ON", 1],
                valueOff: ["OFF", 0],
                cluster: "msCO2",
                attribute: {ID: 0x0211, type: 0x10},
                description: "Enable or Disable light indicator",
				access: "STATE_SET",
            }),
            numeric({
                name: "light_indicator_level",
                unit: "%",
                valueMin: 0,
                valueMax: 100,
                cluster: "msCO2",
                attribute: {ID: 0x0209, type: 0x20},
                description: "Light indicator level",
				access: "STATE_SET",
            }),
			numeric({
                name: "temperature_offset",
                unit: "°C",
                valueMin: -50,
                valueMax: 50,
                valueStep: 0.1,
                scale: 10,
                cluster: "msTemperatureMeasurement",
                attribute: {ID: 0x0410, type: 0x29},
                description: "Adjust temperature",
                access: "STATE_SET",
            }),
            numeric({
                name: "humidity_offset",
                unit: "%",
                valueMin: -50,
                valueMax: 50,
                valueStep: 1,
                cluster: "msRelativeHumidity",
                attribute: {ID: 0x0210, type: 0x29},
                description: "Adjust humidity",
                access: "STATE_SET",
            }),
			numeric({
                name: "auto_clean_interval",
                unit: "day",
                valueMin: 0,
                valueMax: 10,
                valueStep: 1,
                cluster: "pm25Measurement",
                attribute: {ID: 0x0330, type: 0x20},
                description: "Auto clean interval PM2.5 sensor",
                access: "STATE_SET",
            }),
            binary({
                name: "manual_clean",
                valueOn: ["ON", 1],
                valueOff: ["OFF", 0],
                cluster: "pm25Measurement",
                attribute: {ID: 0x0331, type: 0x10},
                description: "Manual clean PM2.5 sensor",
                access: "STATE_SET",
            }),
			binary({
                name: "forced_recalibration",
                valueOn: ["ON", 1],
                valueOff: ["OFF", 0],
                cluster: "msCO2",
                attribute: {ID: 0x0202, type: 0x10},
                description: "Start FRC (Perform Forced Recalibration of the CO2 Sensor)",
                access: "STATE_SET",
            }),
            numeric({
                name: "manual_forced_recalibration",
                unit: "ppm",
                valueMin: 0,
                valueMax: 5000,
                cluster: "msCO2",
                attribute: {ID: 0x0207, type: 0x21},
                description: "Start Manual FRC (Perform Forced Recalibration of the CO2 Sensor)",
                access: "STATE_SET",
            }),
            binary({
                name: "automatic_self_calibration",
                valueOn: ["ON", 1],
                valueOff: ["OFF", 0],
                cluster: "msCO2",
                attribute: {ID: 0x0402, type: 0x10},
                description: "Automatic self calibration",
                access: "STATE_SET",
            }),
            binary({
                name: "factory_reset_co2",
                valueOn: ["ON", 1],
                valueOff: ["OFF", 0],
                cluster: "msCO2",
                attribute: {ID: 0x0206, type: 0x10},
                description: "Factory Reset CO2 sensor",
                access: "STATE_SET",
            }),
			binary({
                name: "enable_pm25",
                valueOn: ["ON", 1],
                valueOff: ["OFF", 0],
                cluster: "pm25Measurement",
                attribute: {ID: 0x0220, type: 0x10},
                description: "Enable PM2.5 Control",
				access: "STATE_SET",
            }),
            numeric({
                name: "high_pm25",
                unit: "µg/m³",
                valueMin: 0,
                valueMax: 1000,
                cluster: "pm25Measurement",
                attribute: {ID: 0x0221, type: 0x21},
                description: "Setting High PM2.5 Border",
				access: "STATE_SET",
            }),
            numeric({
                name: "low_pm25",
                unit: "µg/m³",
                valueMin: 0,
                valueMax: 1000,
                cluster: "pm25Measurement",
                attribute: {ID: 0x0222, type: 0x21},
                description: "Setting Low PM2.5 Border",
				access: "STATE_SET",
            }),
			binary({
                name: "enable_co2_gas",
                valueOn: ["ON", 1],
                valueOff: ["OFF", 0],
                cluster: "msCO2",
                attribute: {ID: 0x0220, type: 0x10},
                description: "Enable CO2 Gas Control",
				access: "STATE_SET",
            }),
            numeric({
                name: "high_co2_gas",
                unit: "ppm",
                valueMin: 400,
                valueMax: 5000,
                cluster: "msCO2",
                attribute: {ID: 0x0221, type: 0x21},
                description: "Setting High CO2 Gas Border",
				access: "STATE_SET",
            }),
            numeric({
                name: "low_co2_gas",
                unit: "ppm",
                valueMin: 400,
                valueMax: 5000,
                cluster: "msCO2",
                attribute: {ID: 0x0222, type: 0x21},
                description: "Setting Low CO2 Gas Border",
				access: "STATE_SET",
            }),
            binary({
                name: "enable_voc",
                valueOn: ["ON", 1],
                valueOff: ["OFF", 0],
                cluster: "genAnalogInput",
                attribute: {ID: 0x0220, type: 0x10},
                description: "Enable VOC Control",
				access: "STATE_SET",
            }),
            numeric({
                name: "high_voc",
                unit: "VOC Index points",
                valueMin: 0,
                valueMax: 500,
                cluster: "genAnalogInput",
                attribute: {ID: 0x0221, type: 0x21},
                description: "Setting High VOC Border",
				access: "STATE_SET",
            }),
            numeric({
                name: "low_voc",
                unit: "VOC Index points",
                valueMin: 0,
                valueMax: 500,
                cluster: "genAnalogInput",
                attribute: {ID: 0x0222, type: 0x21},
                description: "Setting Low VOC Border",
				access: "STATE_SET",
            }),
        ],
    };

module.exports = definition;